import Head from "next/head";

export default function Home() {
  return (
    <div className="h-screen p-10">
      <Head>
        <title>BLog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Blog </h1>
    </div>
  );
}
