import Head from "next/head";
import { Header } from "../components";

export default function Home() {
  return (
    <div className="max-w-7xl mx-auto p-4">
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <h1 className="text-3xl">Home</h1>
    </div>
  );
}
